[package]
name = "dfu-core"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
thiserror = "1"
libusb = { version = "0.3", git = "https://github.com/cecton/libusb-rs.git", branch = "add-extra-methods" }
libusb-sys = "0.2"
